### ISSUE TITLE
Paginación en el blog

### ISSUE THREAD

**Issue by hpaez** [iv-devs/iv-devs.github.io#32]
@DMaster69 y @cristofer-dev no pude probar el tema de la paginación en el blog, trate con todo los medios pero no cacho que pasa, ustedes cachan que pasa?

**Comment by DMasterIO** [comment]
yo también estuve mucho tiempo intentándolo y nunca me funciono :/ no se como ayudarte, incluso utilice el repo de @hsalazr por que su paginador si funciona. pero no pude u.u
https://github.com/hsalazr/hsalazr.github.io

**Comment by hpaez** [comment]
vale @DMaster69 voy a investigar en el repo y ver que sale. otra cosa borramos el repo antiguo de la pagina? digo porque ya no se va a utilizar.

**Comment by DMasterIO** [comment]
Me parece bien borrarlo, fue un respaldo en su momento, pero como dices, ya no tiene sentido

**Comment by DMasterIO** [comment]
@hpaez si te interesa, estuve pensando migrar el blog a medium, ya creé la publicación, pero igual hay que ponerle un poco de amor...
https://medium.com/iv-devs

**Comment by hpaez** [comment]
Interesante, voy a ver que tal.
