### ISSUE TITLE
Contactar a PROIN

### ISSUE THREAD

**Issue by cristofer-dev** [iv-devs/iv-devs.github.io#36]
Consultar si seran partners para la conferencia del 2018

**Comment by DMasterIO** [comment]
@cristofer-dev hablé con @DiruzCode y dice en lo personal apoyará la causa en todo lo que necesitemos, y hablará con el Staff para ver si como comunidad apoyan :) (aunque le cree que si)

**Comment by cristofer-dev** [comment]
Nice! Voy a mover esta ISSUE al repo privado para seguir el thread.

**Comment by diruzcode** [comment]
@cristofer-dev @DMaster69 ya hablamos con todos los chicos y estan todos motivamos en apoyarlos en lo que necesiten :D

**Comment by DMasterIO** [comment]
Cool!, @DiruzCode entonces les avisaremos cualquier cosa en la cual necesitemos ayuda, de momento anoten la fecha *18.08.2018, Universidad Santo Tomás, La Serena, Chile* IV Devs *Conf*.

Por ahora si tienen contacto de alguien que pueda/quiera ir como expositor e idealmente su empresa lo sponsore, pasen el dato :P 

![image](https://user-images.githubusercontent.com/5914439/38622221-10d77e44-3d79-11e8-9ca5-880cc6b2ce50.png)
